### ISSUE TITLE
DOCUMENT UPGRADATION AND ENHANCEMENT

### ISSUE THREAD

**Issue by Naren456** [StratOS-Linux/StratVIM#35]
I'd like to make certain changes in the documentations of this code .

Objective:-
1. Making it more engaging and enhancing the full vibe of reading and understanding the code and requirements  

Therefore, kindly assign me hacktober fest label

**Comment by slipstream8125** [comment]
The repo already has the hacktoberfest label. Feel free to put up a PR for the above issue
